apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
  namespace: bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
      - name: bastion
        image: postgres:17-alpine  # Используем образ с PostgreSQL 17
        command: ["/bin/sh"]
        args: 
          - "-c"
          - |
            # Установка дополнительных утилит
            apk add --no-cache \
              curl \
              wget \
              openssh-client \
              bash \
              vim \
              bind-tools
            
            # Настройка SSH
            mkdir -p /root/.ssh
            chmod 700 /root/.ssh
            if [ -f /ssh-key/id_ed25519 ]; then
              cp /ssh-key/id_ed25519 /root/.ssh/
              chmod 600 /root/.ssh/id_ed25519
              echo "SSH key loaded"
            fi
            
            # Настройка PostgreSQL
            mkdir -p /root/.postgresql
            if [ -f /postgres-ca/root.crt ]; then
              cp /postgres-ca/root.crt /root/.postgresql/
              chmod 0600 /root/.postgresql/root.crt
              echo "PostgreSQL CA cert loaded"
            fi
            
            # Создай .pgpass для автоматического ввода пароля
            echo "$PGHOST:$PGPORT:$PGDATABASE:$PGUSER:$PGPASSWORD" > /root/.pgpass
            chmod 0600 /root/.pgpass
            
            # Создай alias для быстрого подключения
            echo 'alias pgconnect="psql"' >> /root/.bashrc
            
            echo "Bastion ready! psql version:"
            psql --version
            
            while true; do sleep 3600; done
        env:
        # PostgreSQL переменные окружения
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: host
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: port
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: dbname
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: password
        - name: PGSSLMODE
          value: "verify-ca"
        - name: PGSSLROOTCERT
          value: "/root/.postgresql/root.crt"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: ssh-key
          mountPath: /ssh-key
          readOnly: true
        - name: postgres-ca
          mountPath: /postgres-ca
          readOnly: true
      volumes:
      - name: ssh-key
        secret:
          secretName: bastion-ssh-key
          defaultMode: 0600
      - name: postgres-ca
        configMap:
          name: postgres-ca-cert
          defaultMode: 0600
