apiVersion: v1
kind: Secret
metadata:
  name: postgres-mentor-service-staging-app
  namespace: postgres
type: Opaque
data:
  host: bWFzdGVyLmU5MzQyYmU1LTY4MTMtNGFmNC1hYTAzLTUxMzYzNjFmOTk4MC5jLmRiYWFzLnNlbGNsb3VkLnJ1
  port: NTQzMg==
  dbname: ZGJfbWFpbg==
  user: bWVudG9yX3NlcnZpY2Vfc3RhZ2luZ19hcHA=
  password: UVdmVFFpY0J6aVlV
  schema: bWVudG9yX3NlcnZpY2Vfc3RhZ2luZw==