apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-port-forward-binding
  namespace: postgres
subjects:
- kind: ServiceAccount
  name: developer-user
  namespace: developers
roleRef:
  kind: Role
  name: postgres-port-forward
  apiGroup: rbac.authorization.k8s.io