apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-port-forward
  namespace: postgres
rules:
# Права на просмотр pods (обязательно для port-forward!)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

# Права на просмотр логов
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

# Права на port-forward (это отдельный subresource)
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["get", "create"]

# Права на просмотр services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
