apiVersion: v1
kind: Service
metadata:
  name: postgres-client
  namespace: postgres
  labels:
    app: postgres-client
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
    app: postgres-client